site: Simples Jekyll Theme

url: 
baseurl: "/"

collections:
  entries:
    output: true
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
#    permalink: /blog/:slug
  projects:
    output: true
#    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "entries"
    values:
      layout: "entry"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

contact-form: https://forms.gle/yHFzkaKFktQdPA3MA
contact-form-fields: [entry.2060260451, entry.685439012, entry.1310894515]